version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_NAME: your_database_name
      DATABASE_USER: your_database_user
      DATABASE_PASSWORD: your_database_password
      DATABASE_HOST: your_database_host
      DATABASE_PORT: your_database_port