# Generated by Django 5.1.7 on 2025-04-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulkcontactenrichment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='contactenrichment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='contactenrichment',
            name='company_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactenrichment',
            name='type',
            field=models.CharField(default='single', max_length=50),
        ),
    ]
